services:
  client:
    build:
      dockerfile: ./Dockerfile
    command: bash
    working_dir: /kafka/bin
    volumes:
      - ./data:/data
      - ./config:/config

  node:
    image: node
    command: bash
    working_dir: /app
    volumes:
      - ./src:/app