services:
  client:
    build:
      dockerfile: ./Dockerfile
    command: bash
    working_dir: /kafka/bin
    volumes:
      - ./data:/data
      - ./config:/config

  node:
    image: node
    command: bash
    working_dir: /app
    volumes:
      - ./src:/app

  python:
    build:
      context: ./src/python
    command: bash
    working_dir: /app
    volumes:
      - ./src/python:/app



  java11:
    build:
      context: ./src/java
    command: bash
    working_dir: /app
    volumes:
      - ./src/java:/app
    
    